# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 67ff3b30f797bd814f9035cbd23d191d13677d6b6e8432399372d258b73c99e48c6195dbbec4e572ec904f1606ac2ff1df86712bcbbd5f0ce7037eac1723dcd4

test:
  secret_key_base: 5721190e0ad4959ec32b655e4d9325b899e57cc624e811fa259d08ee1af6f376914a8b8caa3f575932dd6b87669cd8836c57d9456fd48fa762a248d62e8e7f44

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
